// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7duBOD9E-A5y5qj_Vy5h-tZ6clVNt2sk',
    appId: '1:1046823476221:web:4be20b4597f6bd036fd794',
    messagingSenderId: '1046823476221',
    projectId: 'flutter-app-be62e',
    authDomain: 'flutter-app-be62e.firebaseapp.com',
    storageBucket: 'flutter-app-be62e.appspot.com',
    measurementId: 'G-6RNVHTZ7CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV9iiaxryQwBXFA1Aa2w09z38NXVYBSyE',
    appId: '1:1046823476221:android:79d960018614d8176fd794',
    messagingSenderId: '1046823476221',
    projectId: 'flutter-app-be62e',
    storageBucket: 'flutter-app-be62e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKl-th6Po1ZTZF9nARhSlq9snTFqsAyI',
    appId: '1:1046823476221:ios:9106c300e6c684856fd794',
    messagingSenderId: '1046823476221',
    projectId: 'flutter-app-be62e',
    storageBucket: 'flutter-app-be62e.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyKl-th6Po1ZTZF9nARhSlq9snTFqsAyI',
    appId: '1:1046823476221:ios:346b4eb2aafcb38a6fd794',
    messagingSenderId: '1046823476221',
    projectId: 'flutter-app-be62e',
    storageBucket: 'flutter-app-be62e.appspot.com',
    iosBundleId: 'com.example.flutterapp.RunnerTests',
  );
}
